### ISSUE TITLE
Breaking regression in 0.11.0

### ISSUE THREAD

**Issue by brettgoulder** [graphql/graphql-js#1006]
```
bgoulder-ltm1% node server.js
/Users/bgoulder/code/users/node_modules/graphql/subscription/subscribe.js:27
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(schema, document, rootValue, contextValue, variableValues, operationName, fieldResolver) {
                               ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/bgoulder/code/users/node_modules/graphql/subscription/subscribe.js:27:32
    at Object.<anonymous> (/Users/bgoulder/code/users/node_modules/graphql/subscription/subscribe.js:95:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bgoulder/code/users/node_modules/graphql/subscription/index.js:7:18)
```

I came across this error while just following the [GraphQL tutorial](http://graphql.org/graphql-js/).  I also tested with 0.10.5 and it is working properly. It seems to be an issue just with 0.11.0.

**Comment by wincent** [comment]
Thanks for the report, @brettgoulder. Looking for suspicious items in the commit listing:

```
d7a80b6 0.11.0
d9178f4 remove dead code from buildASTSchema
0eb070f Expanded findBreakingChanges test with missing case. (#993)
0779c36 Update subscribe function to return a Promise of AsyncIterator or ExecutionResult (#918)
24a5038 Throw TypeError when coercing an array into a GraphQLString (#925)
85bfd13 Export "ExecutionArgs" type (#988)
26023b3 Adding a type to a union is now a dangerous change. (#991)
c156180 chore(package): update eslint to version 4.4.1
ee57e28 chore(package): update eslint to version 4.4.0
bb98768 Adding a value to an enum is now a dangerous change.
cbaf79c chore(package): update chai to version 4.1.1
e067f52 chore(package): update flow-bin to version 0.52.0
07a293c chore(package): update mocha to version 3.5.0
9a63126 chore(package): update flow-bin to version 0.51.1
01033b1 chore(package): update eslint-plugin-babel to version 4.1.2
ab0d655 Add missing export for "findBreakingChanges" function
28b2696 chore(package): update flow-bin to version 0.51.0
f660119 Tiny tweak to wording
bf7555f chore(package): update eslint to version 4.3.0
68cccd3 fix directive description lost in extendSchema
```

Most of these are innocuous.

It's the fact that 0779c36 added an `async` keyword, so you do need Babel correctly configured in order to support that (for example with the Regenerator runtime). I didn't think the tutorial explicitly exercises the `subscribe()` though. How far did you get into the tutorial before seeing this error?

**Comment by brettgoulder** [comment]
@wincent I just copied the first [Hello World section](http://graphql.org/graphql-js/#writing-code) into server.js and ran `node server.js`.

**Comment by wincent** [comment]
Ok, I think we'll just rewrite the offending function with `async`. Give me a few minutes to whip-up a PR.
