### ISSUE TITLE
Error caught shows up in console

### ISSUE THREAD

**Issue by jarnojellesma** [graphql/graphql-js#1071]
I have created a minimum reproducible code in this repository: https://github.com/jarnojellesma/feathers-graphql-test-error

The following test shouldn't produce any error messages on the console, because the error is caught with a try/catch statement.
```
const query = gql`
  query {
    foods {
      name
    }
  }
`

it ('can not be fetched when not authenticated', async () => {
  const api = apolloClient();

  try {
    const res = await api.query({ query });
  } catch (e) {
    return
  }
  
  fail('foods can be fetched when not authenticated');
});
```

But even though the error is caught, it still shows up:
```
Test
    foods
Error: Dangit
    at foods (/home/jarno/Desktop/feathers-graphql-test-error-master/src/services/graphql/resolvers.js:4:29)
    at resolveFieldValueOrError (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:498:12)
    at resolveField (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:462:16)
    at /home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:311:18
    at Array.reduce (<anonymous>)
    at executeFields (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:308:42)
    at executeOperation (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:236:122)
    at executeImpl (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:133:26)
    at Object.execute (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/graphql/execution/execute.js:110:229)
    at doRunQuery (/home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/apollo-server-core/dist/runQuery.js:98:26)
    at /home/jarno/Desktop/feathers-graphql-test-error-master/node_modules/apollo-server-core/dist/runQuery.js:22:54
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
      ✓ can not be fetched when not authenticated

  'foods' service
    ✓ registered the service


  2 passing (753ms)
```

The error is thrown by the foods resolver:

```
Query: {
  foods(root, args, { params, Foods }) {
    return Promise.reject(new Error('Dangit'));
  },
}
```

**Comment by leebyron** [comment]
Given your test and repro use Apollo client, my guess is that the error is there or perhaps due to some bad Promise implementation.

I just added this specific test case and it passes as expected.
