### ISSUE TITLE
String coercion broken for Float Scalar type in 14.0.0

### ISSUE THREAD

**Issue by kylezinter** [graphql/graphql-js#1513]
I was noticing in the release notes that there is stricter coercion introduced with this release per the spec. But I believe there might be an issue with the Float scalar.

Per the spec.

> GraphQL servers may coerce non‐floating‐point internal values to Float when reasonable without losing information, otherwise they must raise a field error. Examples of this may include returning 1.0 for the integer number 1, or 123.0 for the string "123".

To my understanding, that is saying the Float scalar should handle a string that is a valid number such as "123". I'm receiving errors after upgrading when entering a value like that now. Is my understanding incorrect? 

Stacktrace.
TypeError: Float cannot represent non numeric value: "500"
    at GraphQLScalarType.coerceFloat [as parseValue] (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/type/scalars.js:110:11)
    at coerceValue (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:53:30)
    at coerceValue (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:126:30)
    at /Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:88:27
    at Array.forEach (<anonymous>)
    at forEach (/Users/kylezinter/Developement/launchplan/api/node_modules/iterall/index.js:83:25)
    at coerceValue (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:87:28)
    at coerceValue (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:40:12)
    at coerceValue (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/utilities/coerceValue.js:126:30)
    at getVariableValues (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/execution/values.js:85:54)
    at buildExecutionContext (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/execution/execute.js:196:63)
    at executeImpl (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/execution/execute.js:70:20)
    at Object.execute (/Users/kylezinter/Developement/launchplan/api/node_modules/graphql/execution/execute.js:62:229)
    at doRunQuery (/Users/kylezinter/Developement/launchplan/api/node_modules/apollo-server-core/dist/runQuery.js:124:42)
    at /Users/kylezinter/Developement/launchplan/api/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by IvanGoncharov** [comment]
@kylezinter No problem. Thanks for the investigation.
