### ISSUE TITLE
Map constructor does not accept arguments

### ISSUE THREAD

**Issue by Nabellaleen** [graphql/graphql-js#1588]
Hi,

Trying to launch my react native app on Android, I'm getting this error, linked to the following line in graphql-js : https://github.com/graphql/graphql-js/blob/3595ea922613f3e13a07185407dd70ed45de7a66/src/type/definition.js#L1067

Do you have any hints about this problem ? I think it just pop out, so it's probably not directly a graphql-js bug, but I think you are the ones who could help me the best :)

```
2018-11-29 16:35:15.669 19341-19398/com.getluko.cover.app E/ReactNativeJNI: Got JS Exception: Map constructor does not accept arguments (index.android.bundle:98112)
2018-11-29 16:35:15.669 19341-19398/com.getluko.cover.app E/ReactNativeJNI: Got JS Stack: Map@[native code]
    GraphQLEnumType@index.android.bundle:98112:34
    index.android.bundle:99021:60
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96747:35
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96679:30
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96654:29
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:95399:96
    index.android.bundle:95400:5
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:86833:301
    index.android.bundle:86834:5
    loadModuleImplem
2018-11-29 16:35:15.672 19341-19398/com.getluko.cover.app E/unknown:ReactNative: Exception in native call from JS
    com.facebook.react.devsupport.JSException: Map constructor does not accept arguments (index.android.bundle:98112)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:198)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: Map constructor does not accept arguments (index.android.bundle:98112)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:898) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:198) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:764) 
2018-11-29 16:35:15.674 19341-19341/com.getluko.cover.app E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Map constructor does not accept arguments (index.android.bundle:98112)
    
    Map constructor does not accept arguments (index.android.bundle:98112)
    
    Map@[native code]
    GraphQLEnumType@index.android.bundle:98112:34
    index.android.bundle:99021:60
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96747:35
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96679:30
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:96654:29
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:95399:96
    index.android.bundle:95400:5
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:86833:301
    index.android.bundle:86834:5
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:75017:68
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:91:38
    metroRequire@index.android.bundle:72:79
    index.android.bundle:1632:60
    loadModuleImplementation@index.android.bundle:162:14
    guardedLoadModule@index.android.bundle:83:47
    metroRequire@index.android.bundle:72:79
    global code@index.android.bundle:216494:8
```

**Comment by Nabellaleen** [comment]
It's a bug linked to ReactNative js interpreter which didn't have the Map constructor taking an Iterator.

It can be resolved by using a polyfill : https://www.npmjs.com/package/es6-map
