### ISSUE TITLE
GraphQL Stack Traces are (Needlessly) Unhelpful;

### ISSUE THREAD

**Issue by machineghost** [graphql/graphql-js#2215]
Here is a stack trace I recently got:

     Error: Cannot return null for non-nullable field User.id.
        at completeValue (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:560:13)
        at completeValueCatchingError (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:495:19)
        at resolveField (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:435:10)
        at executeFields (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:275:18)
        at collectAndExecuteSubfields (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:713:10)
        at completeObjectValue (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:703:10)
        at completeValue (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:591:12)
        at completeValueCatchingError (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:495:19)
        at resolveField (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:435:10)
        at executeFields (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:275:18)
        at collectAndExecuteSubfields (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:713:10)
        at completeObjectValue (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:703:10)
        at completeValue (/home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:591:12)
        at /home/me/projects/my-project/server/node_modules/graphql/execution/execute.js:492:16

I don't mean to sound ungrateful for awesome free software (that is the best way to build an API today) ... but would it _kill_ you to include the resolver that caused the problem?

**Comment by IvanGoncharov** [comment]
@machineghost Thanks for your report 👍 
It's definitely something we should try to address since I fully agree that current error gives you an absolute minimum of info.
By default JS environments output `description` + `call trace` and we can't include a query or query variables into `description` since they can be huge and `description` is sent to the API client.
However, I definitely agree that we should try to find solutions to provide more details in printed error messages.

At the moment we are in feature freeze due to the upcoming TS conversion but after it's done we will definitely try to address this problem.

**Comment by machineghost** [comment]
Awesome.  Specifically, regarding:

> By default JS environments output description + call trace and we can't include a query or query variables into description since they can be huge and description is sent to the API client.

Fair enough, but even _just_ the first 100 characters of the query (_maybe_ coupled with however many keys of the variables object would fit) would likely be enough to narrow down the source of the error in 95+% cases.

**Comment by machineghost** [comment]
But then you have to catch and log the error (specifically as a string) to see that info.

Surely you agree it would be more convenient if a developer can 1) get an error, 2) immediately determine where it came from?  Surely you agree that if the entire problem is that you *can't* tell where the error came from, being able to get more info when you log it (AFTER you find it) isn't very helpful?

**Comment by IvanGoncharov** [comment]
@machineghost I definitely agree with all your points just wanted to specify that it's possible to do using the above workaround.

**Comment by Markus-ipse** [comment]
This issue is still very much valid, the error messages are really not helpful at all.
See the below one for instance - based on it I have no idea where to look or what to even look for :( 
![image](https://user-images.githubusercontent.com/830794/122550850-7bdeae00-d034-11eb-9ac0-df1173cb53e2.png)

Is there any work ongoing that is trying to remedy this?

**Comment by yaacovCR** [comment]
Feature-freeze over, this issue is open for business.
