### ISSUE TITLE
Improve syntax error message 

### ISSUE THREAD

**Issue by sytranvn** [graphql/graphql-js#3148]
# Feature requests
Currently the error message is not so friendly. If I updated multiple files and then build fail I can not see where the error could be.
```gql
  enum MODE {
    SINGLE
    MUL_OFFLINE
    MUL_ONLINE
  }
  type Game {
    id: ID!
    mode: MODE!
    code: Int
    players: [Player!]!
    properties: [Properties!]!
    cells: [Cell!]!
  }

  type Query {
    game($id: ID!): Game!
  }

  mutation NewGame : Game {
    newGame {
      id
      code
    }
  }

  mutation EndTurn($p: Player) {
    endTurn(player: $p) {
      player {
        id
      }
    }
  }
```
```
/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1413
    throw (0, _syntaxError.syntaxError)(this._lexer.source, token.start, "Expected ".concat(getTokenKindDesc(kind), ", found ").concat(getTokenDesc(token), "."));
    ^

GraphQLError [Object]: Syntax Error: Expected Name, found "$".
    at syntaxError (/Users/sytran/Code/test/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1413:40)
    at Parser.parseName (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:98:22)
    at Parser.parseInputValueDef (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:911:21)
    at Parser.optionalMany (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseArgumentDefs (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:900:17)
    at Parser.parseFieldDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:880:21)
    at Parser.optionalMany (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseFieldsDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:868:17)
    at Parser.parseObjectTypeDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:812:23) {
  locations: [ { line: 17, column: 10 } ]
}
```

I suggest the message should show the line where token is in valid.
```
/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1413
    throw (0, _syntaxError.syntaxError)(this._lexer.source, token.start, "Expected ".concat(getTokenKindDesc(kind), ", found ").concat(getTokenDesc(token), "."));
    ^

GraphQLError [Object]: Syntax Error: Expected Name, found "$".
    game($id: ID!): Game!
         ^

    at syntaxError (/Users/sytran/Code/test/node_modules/graphql/error/syntaxError.js:25:10)
    at Parser.expectToken (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1413:40)
    at Parser.parseName (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:98:22)
    at Parser.parseInputValueDef (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:911:21)
    at Parser.optionalMany (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseArgumentDefs (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:900:17)
    at Parser.parseFieldDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:880:21)
    at Parser.optionalMany (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseFieldsDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:868:17)
    at Parser.parseObjectTypeDefinition (/Users/sytran/Code/test/node_modules/graphql/language/parser.js:812:23) {
  locations: [ { line: 17, column: 10 } ]
}
```

**Comment by sytranvn** [comment]
I'm able to fix my code but it is still hard to debug the error imo.

**Comment by sytranvn** [comment]
if any one have the same problem, put your code in a `try catch` blog and log the `error.toString()` to view details.
