### ISSUE TITLE
Error: Expected undefined to be a GraphQL schema. on version 16.0.1

### ISSUE THREAD

**Issue by zorro** [graphql/graphql-js#3359]
node: 16.13.0
graphql-js: 16.0.1
I tried to run this example from official documentation : 

```js
var { graphql, buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

// The root provides a resolver function for each API endpoint
var root = {
	hello: () => {
		return 'Hello world!';
	},
};

// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }', root).then((response) => {
	console.log(response);
});
```

and got this error:

```
/home/arunz/Downloads/graphql/node_modules/graphql/type/schema.js:35
    throw new Error(
          ^

Error: Expected undefined to be a GraphQL schema.
    at assertSchema (/home/arunz/Downloads/graphql/node_modules/graphql/type/schema.js:35:11)
    at validateSchema (/home/arunz/Downloads/graphql/node_modules/graphql/type/validate.js:34:28)
    at graphqlImpl (/home/arunz/Downloads/graphql/node_modules/graphql/graphql.js:52:64)
    at /home/arunz/Downloads/graphql/node_modules/graphql/graphql.js:21:43
    at new Promise (<anonymous>)
    at graphql (/home/arunz/Downloads/graphql/node_modules/graphql/graphql.js:21:10)
    at Object.<anonymous> (/home/arunz/Downloads/graphql/hello.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```
No error with graphql-js version 15.7.2

**Comment by IvanGoncharov** [comment]
@zorro Please use named arguments, since it's expected breaking change.
Please see #2904 for the details.

**Comment by IvanGoncharov** [comment]
Keeping it open since it would be a good idea to add temporary `devCheck` to `graphql`/`execute`/subscribe` to make this change less surprising.

**Comment by OmgImAlexis** [comment]
> @zorro Please use named arguments, since it's expected breaking change. Please see #2904 for the details.

Might want to update the README to prevent users running into this.

**Comment by OmgImAlexis** [comment]
Also what are the arguments meant to be? I would have expected `schema` and `query` and yet this throws an error.

```js
const {
    graphql,
    GraphQLSchema,
    GraphQLObjectType,
    GraphQLString,
  }  = require( 'graphql');
  
  var schema = new GraphQLSchema({
    query: new GraphQLObjectType({
      name: 'RootQueryType',
      fields: {
        hello: {
          type: GraphQLString,
          resolve() {
            return 'world';
          },
        },
      },
    }),
  });

  var query = '{ hello }';

graphql({
    schema,
    query
}).then((result) => {
  // Prints
  // {
  //   data: { hello: "world" }
  // }
  console.log(result);
});
```

**Comment by OmgImAlexis** [comment]
Seems it's expecting `source` instead of `query` which really isn't obvious and I honestly feel is going to be confusing for new users.

**Comment by Cobertos** [comment]
Still receiving this issue on the latest install.

Are there more up to date docs? I was going to make a PR to update the README but it looked like there was a big overhaul/redo of the docs?

**Comment by LilDev1l** [comment]
when will the documentation be updated

**Comment by Shaji18** [comment]
For those real beginner like me.
the correct usage of official doc example might have to be like this (not for sure):
```
graphql({
    schema: schema, 
    source: query, 
    rootValue: root
}).then((response) => {
  console.log(response);
});
```
