### ISSUE TITLE
Test fails (flow)

### ISSUE THREAD

**Issue by nbnotabene** [graphql/graphql-js#379]
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@3.8.9
3 info using node@v6.1.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle graphql@0.5.0~pretest: graphql@0.5.0
6 silly lifecycle graphql@0.5.0~pretest: no script for pretest, continuing
7 info lifecycle graphql@0.5.0~test: graphql@0.5.0
8 verbose lifecycle graphql@0.5.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle graphql@0.5.0~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/graphql-js/node_modules/.bin:/usr/bin:/home/nb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
10 verbose lifecycle graphql@0.5.0~test: CWD: /var/www/graphql-js
11 silly lifecycle graphql@0.5.0~test: Args: [ '-c', 'npm run lint && npm run check && npm run testonly' ]
12 silly lifecycle graphql@0.5.0~test: Returned: code: 1  signal: null
13 info lifecycle graphql@0.5.0~test: Failed to exec test script
14 verbose stack Error: graphql@0.5.0 test: `npm run lint && npm run check && npm run testonly`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid graphql@0.5.0
16 verbose cwd /var/www/graphql-js
17 error Linux 3.13.0-85-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
19 error node v6.1.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error graphql@0.5.0 test: `npm run lint && npm run check && npm run testonly`
22 error Exit status 1
23 error Failed at the graphql@0.5.0 test script 'npm run lint && npm run check && npm run testonly'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the graphql package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint && npm run check && npm run testonly
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs graphql
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls graphql
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by leebyron** [comment]
Can you include some information about what version of npm and node are you using? Have you ensured your node_modules folder is installed? You can try `rm -rf node_modules && npm install` to be sure.

**Comment by leebyron** [comment]
I ask because the error stack in that message traces to `npm`

**Comment by nbnotabene** [comment]
2 info using npm@3.8.9
3 info using node@v6.1.0
Tried to reinstall node modules (rm -rf node_modules && npm install)
Same outcome!?

**Comment by robzhu** [comment]
@nbnotabene Are you still having this problem? I was unable to repro this issue just now with npm v3.8.9 and node v6.1.0 on ubuntu 14.04 x64.

**Comment by robzhu** [comment]
@nbnotabene I'm closing this issue, let me know if you hit it again.
