### ISSUE TITLE
Make GraphQLError have a writeable `.stack` property

### ISSUE THREAD

**Issue by alexturek** [graphql/graphql-js#439]
Bluebird checks to see if `stack` is a writeable property on a rejected object, and (incorrectly) warns that the object being rejected with is not an error.

[Offending bluebird line](https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L257)

If the property `stack` was made writeable ([here](https://github.com/graphql/graphql-js/blob/master/src/error/GraphQLError.js#L37)), Bluebird would shut up.

Otherwise, when I throw an error out of an ApolloServer resolver, I see a lot of
```
[grunt-develop] > Warning: a promise was rejected with a non-error (OR WAS IT): [object Error]
    at /Users/aturek/project/node_modules/graphql/execution/execute.js:518:22
From previous event:
    at Promise.then (/Users/aturek/project/node_modules/sequelize/lib/promise.js:24:17)
    at completeValue (/Users/aturek/project/node_modules/graphql/execution/execute.js:510:19)
    at completeValueCatchingError (/Users/aturek/project/node_modules/graphql/execution/execute.js:466:21)
    at resolveField (/Users/aturek/project/node_modules/graphql/execution/execute.js:438:10)
    at /Users/aturek/project/node_modules/graphql/execution/execute.js:243:18
    at Array.reduce (native)
    at executeFields (/Users/aturek/project/node_modules/graphql/execution/execute.js:240:42)
    at executeOperation (/Users/aturek/project/node_modules/graphql/execution/execute.js:181:10)
    at /Users/aturek/project/node_modules/graphql/execution/execute.js:97:13
<truncated>
```

I can make this change if people sign off on it

**Comment by alexturek** [comment]
See also: https://github.com/petkaantonov/bluebird/issues/1146#issuecomment-229076868

**Comment by leebyron** [comment]
Wow, that's kind of annoying.

It makes my heart hurt a little bit to enable overwriting the stack information but let me see if I can't fix this.

**Comment by alexturek** [comment]
I actually assume they're doing it with good intentions; namely so they can rewrite the stack to support more frames (i.e. trace the provenance of the Promise).

But yeah, I get it. Mutable data 👎
