### ISSUE TITLE
Stack traces are getting lost

### ISSUE THREAD

**Issue by gajus** [graphql/graphql-js#770]
I have a query that results in an error.

All I get in the error is the original site:

```
Error: Resource not found.
    at exports.many (/Users/gajus/Documents/dev/gajus/mightyql/dist/index.js:84:11)

```

Which is good..., but not good enough for a lot of cases.

Usually, I'd expect to be able to use `longjohn` to get the full stack trace. In this case, I'd expect output to be:

```
Error: Resource not found.
    at exports.many (/Users/gajus/Documents/dev/gajus/mightyql/dist/index.js:86:11)
---------------------------------------------
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/showtime-api/src/bin/server.js:42:9)
    at Module._compile (module.js:571:32)
    at loader (/Users/gajus/Documents/dev/applaudience/showtime-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gajus/Documents/dev/applaudience/showtime-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/showtime-api/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

```

I still haven't figured out what swallows the stack trace, though.

**Comment by gajus** [comment]
What I've learned from this (rather painful) experience is that `longjohn` does not work with promises, https://github.com/mattinsler/longjohn/blob/5c7a47963cd042253fff578cbb2d26555870f48c/lib/longjohn.coffee#L132-L139 Or at least I cannot see how it could from this code snippet.

What I've also learned is that Chrome devtools have an `async` flag which can be used to produce complete stack traces.

<img width="1920" alt="screen shot 2017-03-24 at 14 47 15" src="https://cloud.githubusercontent.com/assets/973543/24299357/e884de2e-10a0-11e7-841a-0adc2f00c6e6.png">

Therefore, in case there is a need to trace back an issue with a premature stack trace log, start GraphQL server using `node --inspect` and chase the issue.
