### ISSUE TITLE
Consuming Relay Modern artifacts (persisted queries)

### ISSUE THREAD

**Issue by unirey** [graphql/graphql-js#873]
How are `relay-compiler` generated artifacts intended to be consumed by `graphql-js`? [`execute`](http://graphql.org/graphql-js/execution/)? And feed in the whole generated object as a `documentAST` argument? What if there are multiple generated files per query/mutation (fragments)? Only root or  merge somehow?

[`graphql`](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L91-L111) also uses [`validate`](http://graphql.org/graphql-js/validation/). Is it safe to skip this step? It seems to only validate the AST, not variables, I don't see the point to use this if queries are compiled on build-time and persisted, correct me if Im wrong.

---

Here's my (failed) attempt, it seems that 'vanilla' artifact is not meant for this or something is missing:

### Error:
```
TypeError: Cannot read property 'forEach' of undefined
at buildExecutionContext (/node_modules/graphql/execution/execute.js:163:23)
at execute (/node_modules/graphql/execution/execute.js:110:17)
at exports.handler (/index.js:39:3)
```

### Code:

```js
  const {validate, execute} = require('graphql');
  const schema = require('./schema.js');
  const artifact = require('./artifact.js'); // root artifact from next codeblock

  console.log(validate(schema, artifact)); // returns empty array

  execute(schema, artifact) // also tried artifact.query
  .then(result => result)
  .catch(err => {
    throw new Error(err);
  });
```

### "Root" artifact generated:

```js
'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query appQuery {
  viewer {
    ...profile
  }
}

fragment profile on Viewer {
  me {
    firstName
    ...language_list
    id
  }
}

fragment language_list on User {
  languages {
    ...language_item
  }
}

fragment language_item on Language {
  language
  level
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "appQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "profile",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "appQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "appQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "User",
            "name": "me",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "firstName",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Language",
                "name": "languages",
                "plural": true,
                "selections": [
                  {
                    "kind": "InlineFragment",
                    "type": "Language",
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "language",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "level",
                        "storageKey": null
                      }
                    ]
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": null
};

module.exports = batch;
```

### Also generates 2 more files for fragments, not sure if and how to use:

```js
'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type language_list = {|
  +languages: ?$ReadOnlyArray<?{| |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "language_list",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Language",
      "name": "languages",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "language_item",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
```

```js
'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type language_item = {|
  +language: ?string;
  +level: ?"A1" | "A2" | "B1" | "B2" | "C1" | "C2";
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "language_item",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "language",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "level",
      "storageKey": null
    }
  ],
  "type": "Language"
};

module.exports = fragment;
```

**Comment by wincent** [comment]
How are `relay-compiler` generated artifacts intended to be consumed by `graphql-js`?

They not intended to be consumed directly. Almost the opposite: the compiler consumes the `graphql-js` AST and produces an IR (intermediate representation) that is more convenient to work with. That output is used by Relay's own runtime.

The Relay-generated files contain string representations of the queries/fragments, and it's those that can be sent to a `graphql-js`-powered server (either as strings, or persisted to a database and read from there instead).

**Comment by unirey** [comment]
@wincent Ah, I see. That makes sense.

GraphQL server has to parse and validate the query (to AST) which would happen every request. Im not familiar with all the details under GraphQL hood but this seems to be one of the most expensive part of GraphQL at first glimpse, especially if queries are several Kb. 

Wouldn't it make sense to pre-`parse` and pre-`validate` the query and store the AST instead (persisted)?

**Comment by wincent** [comment]
That's definitely an optimization that you can do @unirey. My understanding is that at Facebook, we run validation at query persistence time (ie. when saving the query to the database), and we can skip it at runtime because we know anything we read out of the database has already been validated. On the other hand, a string query (for example one sent from GraphiQL) needs to be validated before execution.

(Not intimately familiar with our server implementation, which is written in Hack and is independent of the `graphql` JS package. It *may* be that we don't implement this optimization, but I know that it is possible.)
